#!/usr/bin/env bash
## -*- sh-basic-offset: 2 -*-
set -x

if [ ! -d "be-tree" ]; then
    git clone -b 'patch/close-dot-file' --single-branch --depth 1 git@github.com:kaustuk-samsung/be-tree.git
    cd be-tree
    make NIF=true
fi

